### ISSUE TITLE
Authentication using SharedKeyCredential throws an error when correct username and wrong secret key is given but getting stuck when wrong account name is given

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-storage-blob-go#103]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/4167
```
**credential, err := azblob.NewSharedKeyCredential(accountName, accountKey)**
```

Error is thrown when wrong account key is given but when the account Name is wrong there is no error thrown but the program eventually times out.

**Comment by zezha-msft** [comment]
Hi @jhendrixMSFT, thanks for letting us know!

This is a known issue. Basically, if the account name is wrong, a DNS error is returned. We retry this type of error, since it might be temporary as well. We don't have a better solution right now, but we are open to suggestions!

**Comment by jhendrixMSFT** [comment]
@PreethamTK who opened the original issue.

**Comment by PreethamTK** [comment]
Is there any better way to check credentials then ?

**Comment by zezha-msft** [comment]
Hi @PreethamTK, what do you mean?

If an account doesn't exist, we get a DNS error, which is the exact same error if the DNS server was misbehaving, so we couldn't really tell whether an account is really non-existent. On the other hand, if an account key is wrong, we know for sure since a 403 is returned from the service.

**Comment by zezha-msft** [comment]
@PreethamTK I'm closing this for now, but please let me know if you have any other question.
