### ISSUE TITLE
[Proposal] High-level APIs should support to taking io.WriterAt as output

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-storage-blob-go#119]
### Which version of the SDK was used?
Latest

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
No support for io.writerAt.

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
Mitigate by writing directly to a file.

### Description
I am writing a plugin for a parallel file system to archive back to BLOB storage.  The current implementation handles the IO but requires io.reader for upload and io.writerAt for download.  There is currently no support for io.writerAt.  Would it be possible to add?

**Comment by JeffreyRichter** [comment]
Specifically, which function(s) do you want support for io.WriterAt?
There are currently no uses of io.Writer anywhere in the code base that we could turn into support for io.WriterAt.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

**Comment by edwardsp** [comment]
I'm very new to go (this is the first thing I've even written...) but I'm implementing this for Azure BLOB:

- https://github.com/edwardsp/lemur/blob/master/cmd/lhsm-plugin-s3/mover.go#L174

This uses the following AWS function:

- https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/download.go#L146

**Comment by JeffreyRichter** [comment]
There is only 1 type in the Go standard library that implements the io.WrterAt interface: os.File. And having multiple goroutines writing to a file using its WriteAt method is not guaranteed to be done in parallel which negatively impacts performance quite significantly.

So, our client library instead offers a DownloadBlobToFile method<https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L243> which take an os.File and memory-maps it into memory which is guaranteed to allow parallel writes by multiple goroutines thereby guaranteeing great performance. We could introduce a DownloadBlobToWriterAt method that takes an io.WriterAt parameter and uses that instead of the file. But, I’m afraid that customers might accidentally use it and experience worse performance. However, if you can’t use DownloadBlobToFile for your scenario, then you could easily create your own DownloadBlobToWriterAt method by taking our code for our private downloadBlobToBuffer method and replace the byte slice with an io.WriterAt; you’ll have to change the call to io.ReadFull<https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/highlevel.go#L222>.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)
