### ISSUE TITLE
(Question) Multithreading Uploads to a container

### ISSUE THREAD

**Issue by kwontae** [Azure/azure-storage-blob-go#155]
### Which version of the SDK was used?
latest
### Which platform are you using? (ex: Windows, Linux, Debian)
Linux
### What problem was encountered?
Have a feature that will be getting many json data from an API (Basically iterating through next page token). I want to use a pool of goroutines that will upload these json objects to a container, but I couldn't find any good explanation nor examples that achieves this. I was wondering what the best practice is when it comes to multithreading uploads to azure blob storage? Do I need to create a blob pipeline per goroutine or do i only need to create a new block blob url per goroutine?

**Comment by zezha-msft** [comment]
Hi @kwontae, thanks for reaching out!

You can use the same pipeline for all Go Routines, but in order to upload to different blobs, you need to create different BlockBlobURLs, because they contain the URL that points to the blobs. 

To achieve concurrent upload, you can spin up a number of Go Routines, and have them listen on a channel, where you publish the URLs to blobs, and the routines would create their own BlockBlobURL to invoke the upload method if the files are small, or call [UploadFileToBlockBlob](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#UploadFileToBlockBlob) which breaks down a larger file for you and issues concurrent requests.
