### ISSUE TITLE
What's the easiest way of getting all the versionIDs for a blob?

### ISSUE THREAD

**Issue by deep-nag** [Azure/azure-storage-blob-go#250]
The API [reference](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob) didn't have a clear answer

**Comment by siminsavani-msft** [comment]
Hi! There are many ways to get versionIDs for blobs. VersionIDs can be found in responses returned by multiple methods such as GetProperties, SetMetadata, etc and can be accessed using the VersionId() method mentioned in API reference (https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob). I've listed a few examples below to help!

You can refer to the tests to help in getting the versionID (https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_blob_versioning_test.go). 

Here are a few examples: 
1. Digging through the rawResponse:
https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/zt_blob_versioning_test.go#L70

2. Using VersionId() method: 
https://github.com/Azure/azure-storage-blob-go/blob/d80c8c7c7c4385e4afe4ebdaab9b31efd7d87eb1/azblob/zt_blob_versioning_test.go#L29

Please let me know if you need any extra clarification!

**Comment by maaft** [comment]
The question was about getting **all** available VersionIDs for a blob. How can I do this?

**Comment by siminsavani-msft** [comment]
Hi @maaft ! You can use the ListBlobsFlagSegment() method to get all the versions. 
https://github.com/Azure/azure-storage-blob-go/blob/b32b5e3579400739418747a71c4bffaf8a19c4a0/azblob/url_container.go#L236

Here is an example from the test file zt_blob_verisioning.go:
https://github.com/Azure/azure-storage-blob-go/blob/b32b5e3579400739418747a71c4bffaf8a19c4a0/azblob/zt_blob_versioning_test.go#L108

This test file has other examples as well! Since you are trying to get versions for a specific blob, I would recommend adding a prefix in the ListBlobSegmentOptions. So something like this:

`listResp, err := containerURL.ListBlobsHierarchySegment(ctx, marker, <delimiter>, ListBlobsSegmentOptions{Prefix: <blobname>, Details: BlobListingDetails{Versions: t.true}})`

I hope this helps! Let me know if you have any other questions!
