### ISSUE TITLE
[Proposal] High-level APIs should support to taking io.Reader as input

### ISSUE THREAD

**Issue by rjtsdl** [Azure/azure-storage-blob-go#31]
> The high-level APIs provide convenience abstractions such as uploading a large stream to a block blob (using multiple PutBlock requests).

Which API shall i use?  (I know we can PutBlock(s) and PutBlockList, but this is not the high-level API)
So is ` BlobURL.StartCopy` the high-level API? Is it support 4TB ?

## Update the description below
Now we have 
`UploadFileToBlockBlob` to take `io.File`
`UploadBufferToBlockBlob` to take `[]byte`

**Propose** to have a new function to take `io.Reader` as input.
btw `http.Response.Body` is `io.ReadCloser`

**Comment by rjtsdl** [comment]
@seguler , thx 
I have been using storage sdk for months. (with the azure-sdk-for-go). I experienced the pain there. 
The only reason I want to look into the new sdk is basically, the high-level API features.

For `UploadFileToBlockBlob ` function, is there another function takes `io.ReadCloser` as input ? This is the most common input type.

**Comment by seguler** [comment]
Then why not use PutBlock and PutBlockList instead ? 

The reason this function takes *os.File is so that we optimize for throughput by the use of memory mapped files and concurrent connections. If we took io.ReadCloser we couldn't do that, could we ?

@giventocode @JeffreyRichter to comment

**Comment by rjtsdl** [comment]
@seguler , we already did that with azure-sdk-for-go. (We don't want to stay on the deprecating sdk)
This is not blocking us. It is blocking us to onboard the new sdk. I want to see the gain to adopt new sdk.

**Comment by JeffreyRichter** [comment]
In or deer to support retries, the new SDK requires a ReadSeeker passed to all upload apis. Your steam may also offer Close and or API will call it if it does.

How are you getting your steam? If from a file, then it will support seeking and if from a memory buffer, you should also have seeking.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by JeffreyRichter** [comment]
Actually, if you don't have a file, then you can call UploadBufferToBlockBlob. UploadFileToBlockBlob calls this internally but it is a public function you can call directly if you have a buffer and not a file.

**Comment by rjtsdl** [comment]
@JeffreyRichter yeah, i checked the source code. And saw `UploadBufferToBlockBlob ` and `UploadFileToBlockBlob `, and one calls another.

The assumption that 
> the new SDK requires a ReadSeeker passed to all upload apis.
is not quite right.

Reading this thread https://stackoverflow.com/questions/37718191/how-do-i-go-from-io-readcloser-to-io-readseeker

if you want to upload something from a simple http.Response.Body (io.ReadCloser), we have to cache it to buffer/file, then upload? 

I guess the reason you had the assumption of ReadSeeker, is because of parallel uploading ? 
I think there is no harm to have one upload to take io.ReadCloser, but potentially could be slow.

**Comment by JeffreyRichter** [comment]
If you want to upload from the network to a blob, then YOU must read the network data into a temporary buffer and then pass a ReadSeeker for the buffer into our SDK upload methods. The reason we require this is to give you retry support. We can perform retries for you over a non-seekable network steam because the data would be lost.

We don't do this for you because we want to let you control the buffer sizes and number of buffers so the you control performance and resources consumption.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by rjtsdl** [comment]
> We can perform retries for you over a non-seekable network steam because the data would be lost.

I think you mean, we cannot ?

**Comment by seguler** [comment]
Yes he meant we CANNOT. We can't seek back to retry

**Comment by rjtsdl** [comment]
Let me share with you guys what s3 takes. 
https://github.com/coreos/etcd-operator/blob/master/pkg/backup/writer/s3_writer.go#L45-L50

I am trying to write similar functionality in etcd-operator project, with this new sdk.  You can see how verbose if using the current functions.

Btw, the interface is this
`Write(ctx context.Context, path string, r io.Reader)`

If S3 can take io.Reader, why we cannot ?

**Comment by giventocode** [comment]
What is not very evident, is that ultimately, the S3 implementation checks if the reader is seekable and if not, copies the data into a buffer, therefore making it seekable. 

https://github.com/aws/aws-sdk-go/blob/b3c93653d2e47b82c5f48d721a2db7778f4e33a8/service/s3/s3manager/upload.go#L542

Under high-stress scenarios, this could significantly increase heap allocations  - even if a pool is used. So is better to provide a seekable stream.

IMHO, explicitly asking for a seekable helps the caller by requiring this functionality upfront instead of giving the impression that seekable/non-seekable streams can be used without an additional impact.

**Comment by rjtsdl** [comment]
I want to clarify, I am not talking about implementation details. ( I do know how they did this, and why we don't do this.)

I am talking about user friendly interfaces. AWS S3 is setting up the standard. We want to catch. The first thing is to follow. Especially, we are creating this new sdk.

**Comment by seguler** [comment]
@JeffreyRichter - it may be worth adding samples to the repo that shows how to read from a non-seekable stream into PutBlob etc...

@rjtsdl - I do not agree. We are not trying to catch up. We are trying to provide the best possible experience, and we decided not to provide APIs that may result in bad programming choices: like buffering a non-seekable stream which will result in bad memory management. By requiring seekable stream, we are being transparent on what is being done in this SDK. Having said this, I am sure this thinking may change/evolve if we get many requests for this.

**Comment by JeffreyRichter** [comment]
I have a ton of respect for what AWS/S3 has done but this does not mean that they have done everything perfectly. My goal is to be a partner to our customer and to help them use Azure Storage correctly and efficiently. Some times, there is a trade-off between giving the user something easy for them to use today but this thing could also burn them later when they are running into resource efficiency problems, or performance issues, or debugging problems. I tried to design our SDK with all these things in mind and my hope is that it is an SDK that provides customers with long term benefit; not just a simple API that works today but hurts them tomorrow.  I also think we are able to show some thought leadership here that may surpass what AWS has dome in some areas. I'd prefer to continue to show thought leadership as opposed to simply following/copying the competition.

**Comment by JeffreyRichter** [comment]
For the sake of technical posterity, I’d like to talk about the issues related to uploading of non-seekable streams. To start, I have decades of experience working with distributed systems and, when it comes to cloud scenarios, success comes from architecting with failure in mind. Specifically, due to the Fallacies of Distributed Computing (http://www.rgoarchitects.com/Files/fallacies.pdf), the only way to get just once semantics is for the client to retry operations and for the service to implement its operations idempotently (I talk about this in depth in a YouTube video here: http://bit.ly/2t7AVew).

So, I feel strongly that our SDKs should have a robust retry mechanism and, to accomplish this, the data being uploaded to the service must be “replayable.” The most efficient way of accomplishing this is by requiring streams to be seekable; so that, on retry, our SDK can seek back to the beginning of the stream in order to resend the same data. We believe that most of our customers’ scenarios involve uploading file data or in-memory buffer data. As both data sources are naturally seekable, our SDK requiring a seekable stream places no hardship on these customer scenarios. 

Of course, some customer scenarios may involve a non-seekable data source. For example, data coming over the network to a PC which, in turn, uploads that data to our service. To accomplish this scenario, each call to our SDK to upload data requires that the network be placed in a buffer first and then a seekable stream over the buffer is passed to our SDK method so that our method can appropriately execute retry operations if necessary. 

Now, you could argue that our SDK should offer this buffering for you automatically. But, let’s think about how this might work. First, what should happen if a failure occurs when reading from the non-seekable stream? Our SDK has no idea how that stream came into existence and has no way to retry whatever operation was used to acquire the stream. So, our SDK can simply fail the operation and your code should manually retry the operation to reacquire the non-seekable stream and call our SDK method again. When passing a seekable stream to our SDK, our SDK method can just retry the operation on your behalf making your code easier to write and maintain.

With a seekable stream, we can seek to the end, get the size, and then seek back to the beginning to upload it. This allows our SDK to make decisions about how to do the upload (in parallel or not) and, we can perform a parallel upload because multiple goroutines/threads can read from different parts of the seekable stream in parallel.

For a non-seekable stream, our SDK methods would have no way of knowing how much data is going to be sent to our service. If you, the customer, knows that the data is 256MB or less, then you can trivially allocate a 256MB buffer, read data from the non-seekable stream into and then call our SDK’s PUT BLOB method to upload the data to our service with retry support. This is very easy for you (about 2-3 lines of code), is inexpensive (one I/O operation to our service) and you can reuse this same memory buffer for other uploads if you’d like so your application is using memory resources efficiently. 

If our SDK automatically allocated a buffer for you, then we don’t know what size to make it; we must pick an arbitrary size and we’d allocate a new buffer with each call to our SDK method and so the buffer is not reusable. This places a larger burden on the garbage collector adversely impacting the performance of your application. One reason why we couldn’t reuse the buffer is because our SDK also doesn’t know if you are calling methods concurrently by multiple goroutines (or threads) and since we must ensure that no corruption occurs, each goroutine/thread must have its own buffer. If each SDK method call allocated a 256MB buffer and you had 10 goroutines/threads calling the method concurrently (not an unreasonable amount), then our SDK is allocating more than 2.5GB on your application’s behalf! We have seen other SDKs that do this cause out-of-memory conditions and garbage collection performance issues in customer’s apps and we don’t want to be responsible for this customer hardship. 

Again, if the customer controls the buffers, then the customer has many options for managing buffer sizes, reusing buffers, controlling concurrency, etc. The customer doesn’t have to understand or reverse engineer what we have done in our SDK to make sure their application runs as they intend it to.

If the size of the data your reading from the non-seekable stream is greater than 256MB, then more questions come into play. Since the non-seekable stream must be read sequentially, there is dubious benefit to performing parallel uploads to our service to increase performance. If reading from the non-seekable stream is faster than uploading to our service, then performance could be improved by allocating multiple buffers and reading from the non-seekable stream into them but again, how many buffers should our SDK allocate? How big should each buffer be? How much faster does the non-seekable stream need to be as compared to the time it takes to upload the data to our service for us to allocate multiple buffers? Should our SDK consume all available memory, or should we leave some memory available for other things your application might want to do? 

Again, the customer knows the character of their data, what kind of hardware their app runs on and if their app is running in the same datacenter as our service (where bandwidth is high) and so on. Our SDK is a general-purpose SDK and we would have to make too many assumptions here that could easily have too adverse an affect. For all these reasons (and more), we have decided not to natively support non-seekable streams in our SDK.

**Comment by fermin-silva** [comment]
Hi Jeffrey, I remember a past discussion with you regarding this topic here: https://github.com/Azure/azure-sdk-for-go/issues/626#issuecomment-324450637

I'll quote you, if you don't mind:
> Now, on top of this building block, a function can be easily implemented that streams a large mass by splitting it into blocks, uploading each block, and then after the last block, calls PutBlockList to assemble the full-size blob. I don't know if the current Go SDK for azure storage has this function but our future Go SDK will definitely have it.

It's common in linux to stream things from one binary to another, it's also a very common thing to do in go, that's why io.reader and io.writer are so powerful and so widely used.
My particular use case is uploading database backups to the cloud. This is very easy to do in Go because I can invoke a program (like xtrabackup, mysqldump, pg_dumpall, etc) and pipe the output into an io.reader. 

Both AWS S3, Google Cloud Storage and Digital Ocean Spaces support that, and I had no problems uploading +1.5TB backups in the past. The SDK does consume some RAM, but I don't mind it, as its reasonable considering how big the stream is !

You pose lot's of questions about how this SDK can't know in advance a lot of variables (buffer size, parallelism, etc). Sorry but that is something very easy to solve: pick a sensible default and let the user configure the rest. 

With S3, if you choose a small part size and the stream ends up being more than 10000 parts, the upload fails. If you choose a huge part size, the upload will be slower in case of a failure (a bigger part must be retried), and the memory requirements will be higher. That's the tradeoff the SDK user has to make

**Comment by fermin-silva** [comment]
Also, I'm not a C# specialist, but I see that the net sdk seems to support it: https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs#L309 making checks to source.CanSeek

**Comment by JeffreyRichter** [comment]
I've been thinking a lot about this problem and we have figured out a way to give you what you want in a pretty efficient way. After we do some more testing, we'll add a UploadStreamToBlockBlob function to the azblob package.  This function will take an io.Reader a BlockBlobURL, and some options (like max buffers and buffer size) and read from the io.Reader stream to 1 (or more) buffers and then upload each buffer to (perhaps in parallel) to the blob. Stay tuned.

**Comment by rjtsdl** [comment]
Thanks all in providing feedback to this proposal !
I am really looking forward to get this issue closed !

**Comment by JeffreyRichter** [comment]
The new UploadStreamToBlockBlob function is now available [here](https://github.com/Azure/azure-storage-blob-go/blob/master/2017-07-29/azblob/highlevel.go#L372). Internally, it reads from an io.Reader into 1+ buffers sequentially but can upload those buffers in parallel to create the block blob. Buffers are also reused when they become available. You can configure the max number of buffers & their size. The function should be very efficient, provide good performance, and fully supports retrying/resilience when uploading a buffer to the blob. 

FYI: By default their is no retry/resiliency if something goes wrong with the io.Reader stream. However, if the io.Reader is sourced from an HTTP request, then you could use our [NewRetryReader](https://github.com/Azure/azure-storage-blob-go/blob/master/2017-07-29/azblob/zc_retry_reader.go#L56). to make the reading side resilient too. This works with any kind of HTTP request not just HTTP requests to download blobs.

**Comment by fermin-silva** [comment]
Great news! Looking forward to implement it in our next sprint.
Thank you guys

**Comment by maorfr** [comment]
Hey @JeffreyRichter,

I guess I am late for the party :)

regarding `UploadStreamToBlockBlob` - Is there an equivalent download method?

Thanks!

**Comment by maorfr** [comment]
Thanks a lot!!
