### ISSUE TITLE
API Stability and Versioning

### ISSUE THREAD

**Issue by michaelbironneau** [Azure/azure-storage-blob-go#47]
Hi,

There have been a number of breaking high-level API changes recently. Considering this is still v0.1 there is nothing unusual about that, but we (and probably other Azure-based developers) would benefit from having an idea of when you plan to stabilise the high-level API and how you will version/release thereafter.

A note in the README would be most helpful.

Thanks

Michael

**Comment by tombuildsstuff** [comment]
cc-ing @joshgav (and @katbyte @ptyng from our end) - since we also raised this question IRL recently

**Comment by JeffreyRichter** [comment]
We have been improving the API in response to customer feedback. We also have an internal customer that is using this SDK very heavily and giving us feedback. Our hope is to put this library into General Availability be end of July or August. 

Each SDK subdirectory is tied to a service API version like 2017-07-29. Within an SDK?service API version, we will make backward compatible improvements (like performance improvements or introduction of new APIs); we will NOT change existing API signatures. 

However, when a new service API version comes out, we will introduce a new SDK for it. In this new SDK, we will try hard not to break API signatures but we do not guarantee it. A new service feature may require that we expose a new parameter so that customers can take advantage of it. Also, our SDK exposes a lot of AutoRest-generated data types. Future versions of AutoRest may change how they generate data types and these could cause breaking changes. While this is possible, it is unlikely and, within an SDK/service API version,  we will use the same autorest version to ensure that generated data types do not change allowing us to maintain backwards compatibility within a single SDK/service API version.  We do intend to formally document this versioning strategy as it applies to all of our new, rearchitected SDKs in all languages (Go, Async Java, Node, Python, .NET , etc.).

**Comment by landro** [comment]
Any updates on this @JeffreyRichter ?

**Comment by zezha-msft** [comment]
Hi @landro, thanks for following up! We've exercised the SDK extensively through the [AzCopy project](https://github.com/Azure/azure-storage-azcopy) and polished the rough edges. I expect the SDK to become GA soon after stress testing.

**Comment by michaelbironneau** [comment]
Thanks @zezha-msft - are you able to provide a timeline for the stress testing and GA release?

**Comment by zezha-msft** [comment]
@michaelbironneau I will have a better idea once the work is scheduled. I'll update this thread accordingly. Thanks!

**Comment by landro** [comment]
Are we talking weeks or months?

**Comment by zezha-msft** [comment]
Hi @landro, 1-3 months would be my guess.

**Comment by zezha-msft** [comment]
@landro is this a concern for your use case?

**Comment by landro** [comment]
Indeed, @zezha-msft . We're implementing our entire infra using terraform, and right now soft delete isn't supported due to the api instability. See https://github.com/terraform-providers/terraform-provider-azurerm/issues/1070 for details.

**Comment by landro** [comment]
Why was this closed?

**Comment by mohsha-msft** [comment]
Hey @landro ,

The reason I closed this issue is because we've been working on an updated version of Go blob SDK which will handle yours concerns and bring better design and user experience. We're using options bags (struct which can have more fields) which will stabilize the issue by handling new parameters which gets introduced with release. So we won't be fixing it here. 

Stay tuned for more updates 😄
